services:

  db:
    image: postgres:16-alpine
    container_name: url-shortener-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url-shortener-db
    ports:
      - "5432:5432"
    volumes:
      - url_shortener_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d url-shortener-db"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./src
      dockerfile: UrlShortener/Dockerfile
    container_name: url-shortener-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultDbConnection: "Host=db;Port=5432;Database=url-shortener-db;Username=postgres;Password=postgres"
      ConnectionStrings__RedisConnection: "redis:6379"
      ShortUrl__BaseUrl: "http://localhost:8080"
      Sqids__Alphabet: ${SQIDS_ALPHABET:?SQIDS_ALPHABET required}
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
volumes:
  url_shortener_db_data:
  redis_data: